package org.spring;

import java.text.Collator;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;

public class Type_4 {
    public static void main(String[] args) {
        String input =
                "M172\n" +
                        "M72\n" +
                        "M8603\n" +
                        "M77\n" +
                        "M8604\n" +
                        "M8605\n" +
                        "D6036\n" +
                        "M81\n" +
                        "F1\n" +
                        "F2\n" +
                        "F3\n" +
                        "F4\n" +
                        "F5\n" +
                        "F6\n" +
                        "F7\n" +
                        "F8\n" +
                        "F9\n" +
                        "F10\n" +
                        "F11\n" +
                        "F12\n" +
                        "F13\n" +
                        "F14\n" +
                        "F15\n" +
                        "F16\n" +
                        "F17\n" +
                        "F20\n" +
                        "F21\n" +
                        "F22\n" +
                        "F25\n" +
                        "F29\n" +
                        "F30\n" +
                        "F31\n" +
                        "F32\n" +
                        "F33\n" +
                        "F34\n" +
                        "F35\n" +
                        "F36\n" +
                        "F37\n" +
                        "F38\n" +
                        "F41\n" +
                        "F42\n" +
                        "F43\n" +
                        "F44\n" +
                        "F45\n" +
                        "F46\n" +
                        "F50\n" +
                        "F51\n" +
                        "F55\n" +
                        "F56\n" +
                        "F57\n" +
                        "F58\n" +
                        "F59\n" +
                        "F61\n" +
                        "F66\n" +
                        "F67\n" +
                        "F70\n" +
                        "F71\n" +
                        "F75\n" +
                        "F76\n" +
                        "F77\n" +
                        "F78\n" +
                        "F79\n" +
                        "F81\n" +
                        "F82\n" +
                        "F85\n" +
                        "F86\n" +
                        "F87\n" +
                        "F88\n" +
                        "F89\n" +
                        "F90\n" +
                        "F91\n" +
                        "F92\n" +
                        "F93\n" +
                        "F94\n" +
                        "F100\n" +
                        "F101\n" +
                        "F102\n" +
                        "F103\n" +
                        "F104\n" +
                        "F105\n" +
                        "F106\n" +
                        "F107\n" +
                        "F108\n" +
                        "F109\n" +
                        "F110\n" +
                        "F111\n" +
                        "F112\n" +
                        "F113\n" +
                        "F114\n" +
                        "F115\n" +
                        "F116\n" +
                        "F117\n" +
                        "F118\n" +
                        "F119\n" +
                        "F120\n" +
                        "F121\n" +
                        "F122\n" +
                        "F123\n" +
                        "F124\n" +
                        "F125\n" +
                        "F126\n" +
                        "F127\n" +
                        "F128\n" +
                        "F129\n" +
                        "F130\n" +
                        "F131\n" +
                        "F132\n" +
                        "F133\n" +
                        "F134\n" +
                        "F135\n" +
                        "F136\n" +
                        "F137\n" +
                        "F138\n" +
                        "F139\n" +
                        "F140\n" +
                        "F141\n" +
                        "F142\n" +
                        "F143\n" +
                        "F148\n" +
                        "F149\n" +
                        "F150\n" +
                        "F151\n" +
                        "F152\n" +
                        "F153\n" +
                        "F154\n" +
                        "F160\n" +
                        "F161\n" +
                        "F162\n" +
                        "F163\n" +
                        "F164\n" +
                        "F165\n" +
                        "F166\n" +
                        "F167\n" +
                        "F168\n" +
                        "F169\n" +
                        "F170\n" +
                        "F171\n" +
                        "F172\n" +
                        "F173\n" +
                        "F174\n" +
                        "F175\n" +
                        "F176\n" +
                        "F177\n" +
                        "F178\n" +
                        "F182\n" +
                        "F183\n" +
                        "F184\n" +
                        "F185\n" +
                        "F186\n" +
                        "F192\n" +
                        "F193\n" +
                        "F194\n" +
                        "F195\n" +
                        "F196\n" +
                        "F197\n" +
                        "F198\n" +
                        "F199\n" +
                        "F200\n" +
                        "F201\n" +
                        "F202\n" +
                        "F203\n" +
                        "F204\n" +
                        "F205\n" +
                        "F206\n" +
                        "F207\n" +
                        "F208\n" +
                        "F209\n" +
                        "F210\n" +
                        "F211\n" +
                        "F212\n" +
                        "F213\n" +
                        "F214\n" +
                        "F215\n" +
                        "F216\n" +
                        "F217\n" +
                        "F218\n" +
                        "F219\n" +
                        "F220\n" +
                        "F221\n" +
                        "F222\n" +
                        "F223\n" +
                        "F224\n" +
                        "F225\n" +
                        "F226\n" +
                        "F227\n" +
                        "F228\n" +
                        "F229\n" +
                        "F232\n" +
                        "F233\n" +
                        "F234\n" +
                        "F235\n" +
                        "F236\n" +
                        "F237\n" +
                        "F238\n" +
                        "F239\n" +
                        "F240\n" +
                        "F241\n" +
                        "F242\n" +
                        "F243\n" +
                        "F244\n" +
                        "F245\n" +
                        "F246\n" +
                        "F247\n" +
                        "F248\n" +
                        "F249\n" +
                        "F250\n" +
                        "F251\n" +
                        "F252\n" +
                        "F253\n" +
                        "F254\n" +
                        "F255\n" +
                        "F256\n" +
                        "F257\n" +
                        "F258\n" +
                        "F259\n" +
                        "F260\n" +
                        "F261\n" +
                        "F262\n" +
                        "F263\n" +
                        "F264\n" +
                        "F265\n" +
                        "F266\n" +
                        "F267\n" +
                        "F268\n" +
                        "F269\n" +
                        "F270\n" +
                        "F271\n" +
                        "F272\n" +
                        "F273\n" +
                        "F274\n" +
                        "F275\n" +
                        "F276\n" +
                        "F277\n" +
                        "F278\n" +
                        "F279\n" +
                        "F280\n" +
                        "F281\n" +
                        "F282\n" +
                        "F283\n" +
                        "F284\n" +
                        "F285\n" +
                        "F286\n" +
                        "F287\n" +
                        "F288\n" +
                        "F289\n" +
                        "F290\n" +
                        "F291\n" +
                        "F292\n" +
                        "F293\n" +
                        "F294\n" +
                        "F295\n" +
                        "F296\n" +
                        "F297\n" +
                        "F298\n" +
                        "F299\n" +
                        "F300\n" +
                        "F301\n" +
                        "F302\n" +
                        "F303\n" +
                        "F304\n" +
                        "F305\n" +
                        "F310\n" +
                        "F311\n" +
                        "F312\n" +
                        "F313\n" +
                        "F314\n" +
                        "F315\n" +
                        "F316\n" +
                        "F317\n" +
                        "F318\n" +
                        "F328\n" +
                        "F329\n" +
                        "F330\n" +
                        "F331\n" +
                        "F332\n" +
                        "F333\n" +
                        "F334\n" +
                        "F335\n" +
                        "F336\n" +
                        "F337\n" +
                        "F338\n" +
                        "F339\n" +
                        "F340\n" +
                        "F341\n" +
                        "F342\n" +
                        "F343\n" +
                        "F344\n" +
                        "F345\n" +
                        "F346\n" +
                        "F347\n" +
                        "F348\n" +
                        "F349\n" +
                        "F350\n" +
                        "F351\n" +
                        "F352\n" +
                        "F353\n" +
                        "F354\n" +
                        "F355\n" +
                        "F356\n" +
                        "F357\n" +
                        "F358\n" +
                        "F359\n" +
                        "F360\n" +
                        "F361\n" +
                        "F362\n" +
                        "F363\n" +
                        "F364\n" +
                        "F365\n" +
                        "F368\n" +
                        "F369\n" +
                        "F370\n" +
                        "F371\n" +
                        "F372\n" +
                        "F373\n" +
                        "F374\n" +
                        "F375\n" +
                        "F376\n" +
                        "F377\n" +
                        "F378\n" +
                        "F379\n" +
                        "F380\n" +
                        "F381\n" +
                        "F382\n" +
                        "F383\n" +
                        "F384\n" +
                        "F385\n" +
                        "F386\n" +
                        "F387\n" +
                        "F388\n" +
                        "F389\n" +
                        "F390\n" +
                        "F391\n" +
                        "F396\n" +
                        "F397\n" +
                        "F398\n" +
                        "F399\n" +
                        "F400\n" +
                        "F401\n" +
                        "F402\n" +
                        "F403\n" +
                        "F404\n" +
                        "F405\n" +
                        "F406\n" +
                        "F407\n" +
                        "F408\n" +
                        "F409\n" +
                        "F410\n" +
                        "F411\n" +
                        "F412\n" +
                        "F413\n" +
                        "F414\n" +
                        "F415\n" +
                        "F416\n" +
                        "F417\n" +
                        "F418\n" +
                        "F419\n" +
                        "F420\n" +
                        "F421\n" +
                        "F422\n" +
                        "F424\n" +
                        "F425\n" +
                        "F426\n" +
                        "F427\n" +
                        "F428\n" +
                        "F429\n" +
                        "F430\n" +
                        "F431\n" +
                        "F432\n" +
                        "F433\n" +
                        "F434\n" +
                        "F435\n" +
                        "F436\n" +
                        "F437\n" +
                        "F438\n" +
                        "F439\n" +
                        "F440\n" +
                        "F441\n" +
                        "F442\n" +
                        "F443\n" +
                        "F444\n" +
                        "F445\n" +
                        "F446\n" +
                        "F447\n" +
                        "F448\n" +
                        "F449\n" +
                        "F450\n" +
                        "F451\n" +
                        "F452\n" +
                        "F453\n" +
                        "F454\n" +
                        "F455\n" +
                        "F456\n" +
                        "F457\n" +
                        "F458\n" +
                        "F459\n" +
                        "F460\n" +
                        "F461\n" +
                        "F462\n" +
                        "F463\n" +
                        "F464\n" +
                        "F465\n" +
                        "F466\n" +
                        "F467\n" +
                        "F468\n" +
                        "F469\n" +
                        "F470\n" +
                        "F471\n" +
                        "F472\n" +
                        "F473\n" +
                        "F474\n" +
                        "F475\n" +
                        "F476\n" +
                        "F477\n" +
                        "F478\n" +
                        "F480\n" +
                        "F481\n" +
                        "F482\n" +
                        "F483\n" +
                        "F484\n" +
                        "F485\n" +
                        "F486\n" +
                        "F487\n" +
                        "F488\n" +
                        "F489\n" +
                        "F490\n" +
                        "F491\n" +
                        "F493\n" +
                        "F494\n" +
                        "F495\n" +
                        "F496\n" +
                        "F500\n" +
                        "F501\n" +
                        "F502\n" +
                        "F503\n" +
                        "F504\n" +
                        "F505\n" +
                        "F506\n" +
                        "F507\n" +
                        "F508\n" +
                        "F509\n" +
                        "F510\n" +
                        "F511\n" +
                        "F515\n" +
                        "F516\n" +
                        "F517\n" +
                        "F518\n" +
                        "F519\n" +
                        "F520\n" +
                        "F525\n" +
                        "F526\n" +
                        "F527\n" +
                        "F528\n" +
                        "F529\n" +
                        "F530\n" +
                        "F531\n" +
                        "F532\n" +
                        "F533\n" +
                        "F534\n" +
                        "F535\n" +
                        "F536\n" +
                        "F537\n" +
                        "F538\n" +
                        "F539\n" +
                        "F540\n" +
                        "F541\n" +
                        "F542\n" +
                        "F543\n" +
                        "F560\n" +
                        "F561\n" +
                        "F562\n" +
                        "F563\n" +
                        "F564\n" +
                        "F565\n" +
                        "F566\n" +
                        "F567\n" +
                        "F568\n" +
                        "F569\n" +
                        "F570\n" +
                        "F571\n" +
                        "F572\n" +
                        "F573\n" +
                        "F574\n" +
                        "F575\n" +
                        "F576\n" +
                        "F577\n" +
                        "F578\n" +
                        "F600\n" +
                        "F601\n" +
                        "F602\n" +
                        "F603\n" +
                        "F604\n" +
                        "F605\n" +
                        "F606\n" +
                        "F607\n" +
                        "F608\n" +
                        "F609\n" +
                        "F610\n" +
                        "F611\n" +
                        "F612\n" +
                        "F613\n" +
                        "F614\n" +
                        "F615\n" +
                        "F616\n" +
                        "F617\n" +
                        "F618\n" +
                        "F619\n" +
                        "F620\n" +
                        "F621\n" +
                        "D9600\n" +
                        "ZR57700\n" +
                        "M8606\n" +
                        "D9610\n" +
                        "ZR57030\n" +
                        "ZR57130\n" +
                        "ZR57230\n" +
                        "ZR57330\n" +
                        "ZR57430\n" +
                        "ZR57032\n" +
                        "ZR57132\n" +
                        "ZR57232\n" +
                        "ZR57332\n" +
                        "ZR57432\n" +
                        "ZR57034\n" +
                        "ZR57134\n" +
                        "ZR57234\n" +
                        "ZR57334\n" +
                        "ZR57434\n" +
                        "ZR57025\n" +
                        "ZR57125\n" +
                        "ZR57126\n" +
                        "ZR57127\n" +
                        "ZR57225\n" +
                        "ZR57226\n" +
                        "ZR57325\n" +
                        "ZR57326\n" +
                        "ZR57425\n" +
                        "ZR57426\n" +
                        "ZR57427\n" +
                        "ZR57003\n" +
                        "ZR57102\n" +
                        "ZR57202\n" +
                        "ZR57302\n" +
                        "ZR57402\n" +
                        "ZR57040\n" +
                        "ZR57140\n" +
                        "ZR57240\n" +
                        "ZR57340\n" +
                        "ZR57440\n" +
                        "ZR57041\n" +
                        "ZR57141\n" +
                        "ZR57241\n" +
                        "ZR57341\n" +
                        "ZR57441\n" +
                        "ZR57521\n" +
                        "ZR57520\n" +
                        "ZR57524\n" +
                        "M836\n" +
                        "ZR57042\n" +
                        "ZR57142\n" +
                        "ZR57242\n" +
                        "ZR57342\n" +
                        "ZR57442\n" +
                        "ZR57043\n" +
                        "ZR57143\n" +
                        "ZR57243\n" +
                        "ZR57343\n" +
                        "ZR57443\n" +
                        "ZR57005\n" +
                        "ZR57105\n" +
                        "ZR57205\n" +
                        "ZR57305\n" +
                        "ZR57405\n" +
                        "ZR57006\n" +
                        "ZR57106\n" +
                        "ZR57206\n" +
                        "ZR57306\n" +
                        "ZR57406\n" +
                        "ZR57011\n" +
                        "ZR57111\n" +
                        "ZR57211\n" +
                        "ZR57311\n" +
                        "ZR57411\n" +
                        "ZR57501\n" +
                        "ZR57013\n" +
                        "ZR57113\n" +
                        "ZR57115\n" +
                        "ZR57117\n" +
                        "ZR57213\n" +
                        "ZR57214\n" +
                        "ZR57313\n" +
                        "ZR57315\n" +
                        "ZR57413\n" +
                        "ZR57415\n" +
                        "ZR57417\n" +
                        "ZR57012\n" +
                        "ZR57112\n" +
                        "ZR57114\n" +
                        "ZR57116\n" +
                        "ZR57212\n" +
                        "ZR57214\n" +
                        "ZR57312\n" +
                        "ZR57314\n" +
                        "ZR57412\n" +
                        "ZR57414\n" +
                        "ZR57416\n";
        List<String> data = new ArrayList<>(Arrays.asList(input.split("\n")));
        Collections.sort(data, Collator.getInstance());
        List<String> dataTrain = sort(data);

        System.out.println("Item Name,IsGroupMember,Item Enabled,Variable Enabled,Variable Name,Variable Option,Variable Class,Variable Object Name,Variable Object Option,Class Hierarchy,File Object Delimiter,Description Enabled,Description,Attribute,Link Item,Initialize Enabled,Initialize Data,Initialize Type,Force to Change,Use Empty,Deactivate,Use History,OnChange Events,Deadband Enabled,Deadbnad Min Value,Deadbnad Max Value,Filter Enabled,Filter Min Value,Filter Max Value,Chattering Enabled,Chattering Max Value,Mask Enabled,Mask Value,BCD Enabled,Request Enabled,Request Type,Request Enabled (Write),Request Type (Write),Allowed Min Value,Allowed Max Value,Allowed Step Value,Allowed List,Allowed Default,Misc Data Type,BLOB Size,BLOB Text,EU Unit,Compare Arrays,Extract Linking,Item Type,Link Property,Sub Item,Sub Item Block Size,Sub Item Block Update,Sub Item Parent Name,Sub Item Offset,Sub Item Data Type,Sub Item Unit Size,Sub Item Elem Count,Sub Item Byte Order,Direct Reading,Direct Reading Suppressed Time,Sub Item Offset Unit,Sub Item Bit,Sub Item Bit Position,Parent Item Data Type,Parent Item Unit Size,Parent Item Elem Count,Not Reconnect Judge Item,Server Publishing Setting");

        Scanner scanner = new Scanner(System.in);

        String parentItem = dataTrain.get(0);
        int offset = 0;

        for (int i = 0; i < dataTrain.size(); i++) {

            int address = Integer.parseInt(dataTrain.get(i).replaceAll("\\D+", ""));
            if (i != 0) {

                int previousAddress = Integer.parseInt(dataTrain.get(i - 1).replaceAll("\\D+", ""));

                if (address - 1 != previousAddress) {
                    parentItem = dataTrain.get(i);
                    offset = 0;
                } else {
                    if (address - 1 != previousAddress) {
                        int count = offset / 2 + 1;
                        System.out.println("WordItem" + parentItem + ",False,True,True," + parentItem + ",'ELEM=" + count + ",VT=Bit',0,,,False,\\,True,,1,,False,,3,0,False,False,True,False,False,0,0,False,0,0,False,0,False,0,False,False,12,False,12,,,,,,,,,,True,False,0,0,False,99,0,,0,0,0,0,0,False,0,0,False,0,8209,1," + count + ",False,2");
                    }
                    System.out.println("WordItem" + parentItem + "|" + dataTrain.get(i) + ",False,True,False,,,0,,,False,\\,True,,0,,False,,3,0,False,False,True,False,False,0,0,False,0,0,False,0,False,0,False,False,12,False,12,,,,,,,,,,True,False,0,0,True,0,0,WordItem" + parentItem + "," + offset + ",17,1,1,1,False,0,0,False,0,0,0,0,False,2");
                    offset++;
                }
            } else {
                System.out.println("WordItem" + parentItem + ",False,True,True," + parentItem + ",'ELEM=99,VT=Bit',0,,,False,\\,True,,1,,False,,3,0,False,False,True,False,False,0,0,False,0,0,False,0,False,0,False,False,12,False,12,,,,,,,,,,True,False,0,0,False,99,0,,0,0,0,0,0,False,0,0,False,0,8209,1,99,False,2");
            }
        }
    }

    private static List<String> sort(List<String> list) {
        Collections.sort(list, new Comparator<String>() {
            @Override
            public int compare(String s1, String s2) {

                int number1 = Integer.parseInt(s1.replaceAll("\\D+", ""));
                int number2 = Integer.parseInt(s2.replaceAll("\\D+", ""));

                return number1 - number2;
            }
        });

        return list;
    }
}